version: '3.8'

services:
  zoo1:
    image: confluentinc/cp-zookeeper:7.4.3
    container_name: zoo1 # explicit name, will be listed in list of containers
    hostname: zoo1 # related to network communication(is used in kafka)
    ports:
      - "2181:2181" # host_port:container_port
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181 # default port
      ZOOKEEPER_SERVER_ID: 1 # unique id for each zookeeper server
    volumes:
      - zookeeper-data:/var/lib/zookeeper/data # named volume for zookeeper data

  kafka1:
    image: confluentinc/cp-kafka:7.4.3
    hostname: kafka1
    container_name: kafka1
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9092 # defines how kafka will be accessed from outside
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: EXTERNAL:PLAINTEXT # data is not encrypted while transfering
      KAFKA_INTER_BROKER_LISTENER_NAME: EXTERNAL
      KAFKA_ZOOKEEPER_CONNECT: "zoo1:2181"
      KAFKA_BROKER_ID: 1 # unique id for each kafka broker
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1 # defines how many replicas of the topic will be created
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1 
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1 # minimum number of in-sync replicas
    depends_on:
      - zoo1
    volumes:
      - kafka-data:/var/lib/kafka/data

volumes:
  zookeeper-data:
  kafka-data: